label: Français
pages:
    -
        label: Le Black Hack
        author: Bruno Bord
        version: '1.0'
    -
        label: En complément
        author: Bruno Bord
        version: '1.0'
        filename: additional-things.md
