label: Português Brasileiro
pages:
    -
        label: The Black Hack
        author: Fernando Guedes
        version: '1.1'
    -
        label: Additional Things
        author: Fernando Guedes
        version: '1.0'
        filename: additional-things.md
